### ISSUE TITLE
Understanding mapper.geo.within

### ISSUE THREAD

**Issue by kneelnrise** [cityzendata/warp10-platform#120]
For a sample project, we need to extract a list of values from a square on the map.

I looked at the doc and found `mapper.geo.within` and tried to test it with sample values :

```
NEWGTS 'test' RENAME
10  10 10 0 '(10, 10)' ADDVALUE
20  10 02 0 '(10, 02)' ADDVALUE
30  12 20 0 '(12, 20)' ADDVALUE
40  15 20 0 '(15, 20)' ADDVALUE
50  15 25 0 '(15, 25)' ADDVALUE

// Let's define a square geo zone around the Ile Vierge, near the coastline of Brittany (France)
'POLYGON ((5 5, 5 100, 100 100, 100 5, 5 5 ))'
0.1 true GEO.WKT

mapper.geo.within 0 0 0
5 ->LIST MAP
```

The result of this query is:

```
[{"c":"test","l":{},"a":{},"v":[[50,14.999999986030161,24.99999993480742,0,"(15, 25)"]]}]
```

Only the last one is included into the result, instead of all except "(10, 02)".

Is it a bug or did I make a mistake ?

**Comment by aurrelhebert** [comment]
Try to reduce the "error percentage" parameter for the GEO.WKT function.This occurred as you set a really large area, and some points are in the border. With a thinner granularity, it will be better. Try to set it to 0.01, to make your example works.

**Comment by aurrelhebert** [comment]
If you really want to include all the points in the border, set the boolean inside to false.
For WarpScript or usage question feel free to ask them on our mailing list https://groups.google.com/forum/?hl=en#!forum/warp10-users.
