### ISSUE TITLE
LMAP behavior

### ISSUE THREAD

**Issue by juanmaneo** [cityzendata/warp10-platform#13]
When using LMAP like for example the sample from: http://www.warp10.io/reference/functions/function_LMAP/

[ 42 21 11 ]
<% -1 * %>
LMAP

gives, not always but most times, the following stack:

0: [0,-1,-2]
1: 11
2: 21
3: 42

When I think the following stack is expected: 

0: [-42,-21,-11]
1: 11
2: 21
3: 42

It something wrong ? Maybe I use wrongly LMAP ?

**Comment by hbs** [comment]
The documentation was misleading. The macro is called with the current list index on top of the stack and the element at that index below it.

Doc for LMAP has been corrected.
