### ISSUE TITLE
init file overwrites configuration file

### ISSUE THREAD

**Issue by mehranshakeri** [cityzendata/warp10-platform#131]
Problem is that init file is overwriting some parameters which we expect to set them in configuration file. e.g. LevelDB home folder. 
After setting  `leveldb.home = /some/where/else/data` in configuration file, our Warp10 instance failed. After investigation we found out that this parameter is overwritten in init file. But since I'm not sure what is the process and order of running LevelDB, I couldn't decide what should be the general solution.

In our case we introduced another parameter in init file to have the same value as configuration there. 

If only by having these kind of parameters in configuration file, Warp10 platform can work properly, then they should be not set in init file again, when the configuration file exists.

**Comment by morind** [comment]
Hi Mehran,

Have you created the Warp10 config file on your own before the first start ?
If so, an error may occurs. At first start, that init file forces the leveldb home directory to ${WARP10_HOME}/data
Then, if the WARP10 config file exists it will not be overwritten.
In the same way, if ${WARP10_HOME}/data contains some files, we do not launch the leveldb init.

**Comment by mehranshakeri** [comment]
Hi David,

We are trying to write a script to setup and run Warp10 standalone in our system using init file.
We did two tests. First we changed the LevelDB path in `conf-standalone.template` file and we assumed it will be applied when we run init file for the first time. But it failed. 

Second test, I changed path to LevelDB in my **existing running** instance and created all the files and folders in new path and removed old folder. This way Warp10 couldn't find new path and it created that folder again and LevelDB created its own file there as well.

init output:
```
find: ‘/opt/warp10/data’: No such file or directory
Init leveldb
```

Then I added new path where `/data` was used in init file and it worked fine.

**Comment by morind** [comment]
Patch is in progress.. :)
The Warp config file will become the reference.
If that file exists, init file will take the leveldb.home parameter.
Otherwise, at first start, it will be forced to ${WARP10_HOME}/data

**Comment by mehranshakeri** [comment]
Thanks, 

And what about template? If it's set in template but there is still no configuration? I would like to know to create a custom setup, should we edit init file or template?

**Comment by morind** [comment]
In template, we have:  leveldb.home = ${standalone.home}/data
Init file updates only the standalone.home parameter.
Thus, you can force the leveldb.home parameter in template.

**Comment by mehranshakeri** [comment]
Since you are working on this init file, we came up with another bug :D 
Setting `QUANTUM_START=false` doesn't work as well.

**Comment by morind** [comment]
Yes, the name is quite ambiguous.
This parameter is only to check if Quantum has been started.
To disable Quantum, you have to comment the Quantum plugin in Warp config file. For example:
#warp10.plugins = io.warp10.plugins.quantum.QuantumPlugin

**Comment by mehranshakeri** [comment]
That's actually better .

Another one :D
`warp10-quantum-server` doesn't exist anymore since Quantum is plugin now.

**Comment by morind** [comment]
Thanks Mehran. 
Fixed

**Comment by morind** [comment]
When you update the leveldb_home parameter, do not forget to update the LEVELDB_HOME variable in snapshot.sh.
