### ISSUE TITLE
TOTIMESTAMP WarpScript function is rounding to milliseconds

### ISSUE THREAD

**Issue by starsway** [cityzendata/warp10-platform#14]
Hello,

It seems that the function 'TOTIMESTAMP' is dropping all digits under millisecond.
On a platform where

$ grep timeunit /opt/warp10/warp10/etc/conf-standalone.conf 
warp.timeunits = ns

has been set, this means that the last six digits are zeroed.

Using the script below, one can see that call to 'ISO8601' and then to 'TOTIMESTAMP' does not lead back to the initial timestamp obtained through call to 'NOW', unlike the ad-hoc function 'myTOTIMESTAMP'.

Is this a desired behaviour? In case it is, I will use my own function, but I thought you might want to know about this.

Please note that if you test this through quantum, display of results will be affected by:

https://github.com/cityzendata/warp10-quantum/issues/7

Thanks

WarpScript used to test and get the expected result:

<%
DUP
ISO8601
TOTIMESTAMP
SWAP
TSELEMENTS
6
GET
1000000
%
+
%>
'myTOTIMESTAMP'
STORE

NOW
DUP
ISO8601
DUP
TOTIMESTAMP
3
PICK
$myTOTIMESTAMP
EVAL

**Comment by starsway** [comment]
It seems that digits under milliseconds are lost when calling:

      long timestamp = fmt.parseDateTime((String) top).getMillis() * Constants.TIME_UNITS_PER_MS;

in https://github.com/cityzendata/warp10-platform/blob/master/warp10/src/main/java/io/warp10/script/unary/TOTIMESTAMP.java

**Comment by aurrelhebert** [comment]
Indeed, we will look in to it (Date formater have to be changed to take in account microseconds or nanoseconds).

**Comment by hbs** [comment]
The libray we currently use is joda-time which only supports millisecond precision.

We will have a look at JSR-310 and the new DataTime API to see if it can be a substitute for joda-time.

**Comment by starsway** [comment]
Thank you very much. It is working as expected, now.
