### ISSUE TITLE
Generic error status codes

### ISSUE THREAD

**Issue by StevenLeRoux** [cityzendata/warp10-platform#145]
Many errors have the same return code : 

- Exceeded MADS
- Invalid Token
- Exec Limit raised
- Exceeded DDP

It would be nice to have a fine grained error status codes so that we can better catch the source of the issue.

**Comment by hbs** [comment]
We don't have the notion of error 'code', we simply have error messages. All the errors you mention have different messages.

**Comment by hbs** [comment]
Do you mean you would like to have an additional notion of error 'code' returned as an HTTP header which could differentiate some specific errors?

**Comment by StevenLeRoux** [comment]
Yes, It could be either an HTTP header or a json payload (or even simple plain text...)

Some HTTP status codes could be affected to common errors : 

206 Partial Content           // parsing error, some data points accepted, but not the whole dataset
429 Too Many Requests . // MADS & DDP exceeded
498 Invalid Token             // ...
499 Token Required         // ...
...

**Comment by d33d33** [comment]
Any news?

**Comment by d33d33** [comment]
Ping

**Comment by StevenLeRoux** [comment]
Error codes formatting have recently changed, breaking parsing and putting this subject back on table.

**Comment by miton18** [comment]
Since Warp10 use an HTTP API it should be great to use it at 100% 
:-)

**Comment by hbs** [comment]
What do you mean?
