### ISSUE TITLE
DTW function is not symetric

### ISSUE THREAD

**Issue by papainge** [cityzendata/warp10-platform#169]
DTW implementations has a big problem. As it is a distance, it must be symetric but it is not the case.

Here is the Gist of my tests
https://gist.github.com/papainge/436e827e319f68505ce2ab37d21be080

Compute is your implementation
ComputeMine is my implementation

**Comment by hbs** [comment]
Hi,

DTW is 'distance-like', it is not a distance as for example the distance
inequality is not guaranteed to hold.

Your implementation can indeed find the optimal solution but is in O(n^2)
in terms of space which is not acceptable, the space efficient algorithm
used in WarpScript does not guarantee to find the optimal solution and also
is not symmetrical, but it nevertheless gives a good similarity evaluation
of two series.

Try computing DTW for 2 series of 100k datapoints using your
implementation, it will attempt to allocate an array with 10 billion cells
thus requiring close to 80Gb or RAM. So it's all a matter of compromise.
