### ISSUE TITLE
Building from releases fails

### ISSUE THREAD

**Issue by brianhks** [cityzendata/warp10-platform#177]
I downloaded the source package from your posted releases and tried to build the binaries but failed with this error:

* What went wrong:
A problem occurred evaluating root project 'warp10-platform-1.2.6'.
> Process 'command 'git'' finished with non-zero exit value 128

Looks like your build always expects it to be a git repo.

**Comment by hbs** [comment]
Yeah, that's a side effect of the build process actually trying to
determine the version number from a call to git.

If you clone the repo from github this will not happen as there will be a
tag in git and the version extraction will succeed.

git clone git@github.com:cityzendata/warp10-platform.git
cd warp10-platform
gradle crypto:install; gradle token:install; gradle warp10:pack

will build Warp 10 (in warp10/build/libs).

Mathias.

**Comment by StevenLeRoux** [comment]
You may need thrift-0.9.1 to compile thrift structs.
