### ISSUE TITLE
Issue reading data written with different write tokens which have the same application

### ISSUE THREAD

**Issue by mehranshakeri** [cityzendata/warp10-platform#179]
Hi Warp10 team,

I am not sure this is solved already or not since I can't upgrade my Warp10 for the moment. 
I am using version "1.2.5-rc7".

The problem is with this query:

```
[
 'READ_TOKEN'
 '~className|className'
 {}
 NOW -1
] FETCH
```

I expect this query to return latest data point for one GTS but in my case it returns one GTS with 3 data points.

How come I wrote this query? Well, I have one macro which generates FETCH query and it could happen that based on some conditions one class name will be chosen several times.

My current workaround is to make output of that macro UNIQUE but still I didn't expect Warp10 behave like this. Is this a bug or expected behaviour? And if it's a bug, is it already solved in current version?

Thanks

**Comment by mehranshakeri** [comment]
I just tested another query and it returned totally strange result!

```
[
 'READ_TOKEN'
 'className'
 {}
 NOW -1
] FETCH
0 GET SIZE
```
And result was 3!!

I think I have to upgrade my Warp10!

**Comment by mehranshakeri** [comment]
I found the source of problem. 

There were different write tokens using the same application name.

Now my question is why Warp10 returned them in one single GTSs? because they had the same ".app" label? 
And this result is some expected behaviour?

**Comment by hbs** [comment]
Can you run a FIND with the same selector and post the list of matching GTS?

As a quick fix can you try '~(className|className)' as the selector?

**Comment by mehranshakeri** [comment]
READ_ALL_TOKEN has no application so we can read all applications with this token.

```
'READ_ALL_TOKEN'
'agent.24.mission.1.56'
{}
FIND
```

FIND result:

```
[
 {"c":"agent.24.mission.1.56","l":{".app":"agent.24.mission.1"},"a":{},"v":[]},
 {"c":"agent.24.mission.1.56","l":{".app":"agent.24.mission.1"},"a":{},"v":[]},
 {"c":"agent.24.mission.1.56","l":{".app":"agent.24.mission.1"},"a":{},"v":[]}
]
```

 '~(className|className)' also doesn't work.

As I mentioned, I found out there are 3 write tokens generated for the same application name. When I use a specific read token for one given write token, FETCH returns only one value (I assume the one which is written with corresponding write token). But when I use a general read token which no application is assigned to it, result contains 3 data points in values list.

**Comment by hbs** [comment]
Ok, found the reason of the behavior you are experiencing.

Internal labels .owner and .producer are never exposed, so your 3 GTS which
either have different owner and or producer appear as the same GTS, and the
data points are therefore merged into a single GTS.

Add a label so you can differentiate your GTS.

**Comment by mehranshakeri** [comment]
You mean adding a label when writing data? So when I read them, they will be in separate GTS.

Thank you :D

**Comment by hbs** [comment]
Yes, not having any user defined labels identifying the owner of the data is fine as long as you don't fetch data from GTS which belong to different users at the same time. If you intend to do the latter, you need to have user specific label(s) which will be preserved when fetching the data.
