### ISSUE TITLE
NaN interpreted as 0 if first datapoint in GTS != NaN

### ISSUE THREAD

**Issue by simonfey** [cityzendata/warp10-platform#199]
Adding a "NaN" datapoint inside a GTS behaves strangely.
I had this issue, when I used FILLTICKS to fill with a GTS with NaN.
The first tick in a GTS has to be NaN, otherwise every NaN will be converted to 0 (for the whole GTS).

```
NEWGTS 'test1' RENAME
{ 'label0' '42' 'label1' 'foo' } RELABEL
100  NaN NaN NaN NaN ADDVALUE
200  NaN NaN NaN 42 ADDVALUE
300  NaN NaN NaN NaN ADDVALUE
'test1' STORE

NEWGTS 'test2' RENAME
{ 'label0' '42' 'label1' 'foo' } RELABEL
100  NaN NaN NaN 42 ADDVALUE
200  NaN NaN NaN NaN ADDVALUE
300  NaN NaN NaN NaN ADDVALUE
'test2' STORE

$test1 100 ATTICK 4 GET NaN == ASSERT
$test1 200 ATTICK 4 GET 42 == ASSERT
$test1 300 ATTICK 4 GET NaN == ASSERT

$test2 100 ATTICK 4 GET 42 == ASSERT
$test2 200 ATTICK 4 GET NaN == ASSERT
$test2 300 ATTICK 4 GET NaN == ASSERT
```

```
{"c":"test2","l":{"label0":"42","label1":"foo"},"a":{},"v":[[100,42],[200,0],[300,0]]}
{"c":"test1","l":{"label0":"42","label1":"foo"},"a":{},"v":[[100,NaN],[200,42],[300,NaN]]}
```

**Comment by hbs** [comment]
NaN is a Double, if you attempt to add it to a LONG GTS, then indeed it
will be converted to 0 as NaNs do not make sense for a LONG GTS.

If you add it to a DOUBLE GTS then it will appear as NaN in the values:

NEWGTS
100  NaN NaN NaN 42.0 ADDVALUE
200  NaN NaN NaN NaN ADDVALUE
300  NaN NaN NaN NaN ADDVALUE

**Comment by simonfey** [comment]
ok. I did miss the fact that any first value defines the type of GTS then. thanks.
