### ISSUE TITLE
Make calls to Meta API create series in directory

### ISSUE THREAD

**Issue by StevenLeRoux** [cityzendata/warp10-platform#203]
Hi, 

There are cases where you need to update some metadata, calling /meta API, but since your data points could be issued by counters, they can arrive later.

When Metadata are managed, there are few risks of desync between meta and data.

Another point is : 
- default behaviour should, by default, allow the creation of empty series while calling Meta API.
- If a user deleteall a series, and update Meta that ends to the deprecated series creation. It's up to the user to assume it, and manage its series. "Last Activity" feature will help cleaning these eventualities.

The control over the ability to create series or not could be addressed at two places : 
 - global param for the platform
 - as a boolean inside the WRITE token

IMO, this behaviour is more natural than just forbid the creation of empty series.

**Comment by hbs** [comment]
This cannot be handled this way as calls to /meta do not contribute to the
MADS quota.

If you know some series will be created (since you want to update their
metadata), you can simply create a dummy datapoint at a specific timestamp
to force GTS creation in the directory.

**Comment by StevenLeRoux** [comment]
Meta and Data are often handled separately. It would mean for a customer to maintain a state of what have been initiated with a dummy point sent to prevent from further updates.

**Comment by hbs** [comment]
Your particular use case seems to imply that you know the GTS whose metadata you want to update via /meta, so you may perfectly well push the dummy datapoint prior to calling /meta, therefore ensuring that the GTS exist, as the Kafka messages for the /meta call are pushed to the same topic as those for the new metadata resulting from the call to /update, the attribute update will be performed after the creation of the GTS and the net effect will be the expected one.

**Comment by d33d33** [comment]
We could add meta support on `/update`.
```
1380475081000000// foo{label=val}{meta=foo} 123
```
Combined with #200 it allow user to set metadatas on push (sync) and to update them on `activityWindow` end (async)

**Comment by hbs** [comment]
The parsing of attributes could be enabled in the ingress endpoints via a configuration, but the metadata update mechanism would need to be heavily modified to bypass the cache when attributes are set and to take into account on the Directory side this new type of Metadata.

Also the update could not be made asynchronous for safety reasons.

**Comment by hbs** [comment]
Closing as this will be similarly addressed by #234
