### ISSUE TITLE
Value Type for MAXDEPTH function

### ISSUE THREAD

**Issue by aurrelhebert** [cityzendata/warp10-platform#21]
When using the function MAXDEPTH on Warpscript, a type exeption is thrown ( integer cannot be casted to long). 
In fact in the class : script/functions/MAXDEPTH.java, limit is set to the attribute ATTRIBUTE_MAX_DEPTH
``
stack.setAttribute(WarpScriptStack.ATTRIBUTE_MAX_DEPTH, limit);
``
The problem here is that limit correspond to a Long, when WarpScriptStack.ATTRIBUTE_MAX_DEPTH is set to int.

**Comment by hbs** [comment]
Conversion to an int should be forced.
