### ISSUE TITLE
Better error when calling DELETE function on a inmemory standalone 

### ISSUE THREAD

**Issue by PierreZ** [cityzendata/warp10-platform#216]
When we're using a DELETE on a inmemory standalone, we obtain this error:

```
DELETE failed to complete actual request successfully (Server Error)
```
Warp10's log are holding the real error:
```
Caused by: java.io.IOException: MemoryStore only supports deleting complete Geo Time Series.
```

Is it possible for DELETE function to forward this error from /api/v0/delete?

**Comment by hbs** [comment]
Are you trying to perform a delete on a complete GTS or a timeslice?

**Comment by PierreZ** [comment]
Yes, it's on a timeslice, that's why it's not working... Can the error  be forwarded as a replacement of "(Server Error)"?

**Comment by hbs** [comment]
The error handling is performed by way of exceptions in the servlet engine, it handles the actual error message.
