### ISSUE TITLE
Implicit mutability while using APPEND

### ISSUE THREAD

**Issue by StevenLeRoux** [cityzendata/warp10-platform#217]
Here is an example : 

```
[ 'a' ] 'list' STORE
$list 'b' + DROP
$list

```
The stack contains : **['a']**

```
[ 'a' ] 'list' STORE
$list [ 'b' ]  APPEND DROP
$list
```
The stack contains : **['a','b']**

Since the $list has not been STOREd back, it seems that APPEND is applying mutabilty on the given object.

If this is a normal behaviour, we should point it out in the reference doc for APPEND and other concerned functions.

**Comment by aurrelhebert** [comment]
I think it's something we have to be cautious with. In other language, `APPEND` is also mutable. May be what we are lacking of is a `PUSH` and `POP` mutable functions?

**Comment by LostInBrittany** [comment]
I agree with @aurrelhebert, adding `PUSH` and `POP` would be an elegant way to solve the issue without doing any breaking change.

**Comment by StevenLeRoux** [comment]
PUSH or APPEND, the wording is not really the issue. What matters most it the behaviour behind the word.

**Comment by LostInBrittany** [comment]
I guess than a *mutable* `PUSH` (and `POP`) fit nicely (in a semantic way) with other list and map manipulation functions (`APPEND`, `PUT`...). As I don't see easy modifying all those functions, adding them could make things more uniform (IMHO).

**Comment by hbs** [comment]
The function '+!' was added in novembre 2016 (commit 8562e01669ea895b0535afc8d806f032d59951c6) to allow to add elements to the original list.
