### ISSUE TITLE
New functions to DROP/ADD buckets 

### ISSUE THREAD

**Issue by PierreZ** [cityzendata/warp10-platform#218]
Here's an example:

```
NEWGTS 'toto' RENAME 
10 NaN NaN NaN  3.0 ADDVALUE
20 NaN NaN NaN  10.0 ADDVALUE
30 NaN NaN NaN 16.0 ADDVALUE
40 NaN NaN NaN 40.0 ADDVALUE
1 ->LIST

[ SWAP mapper.rate 1 0 0 ] MAP
```

When running any kind of mapper on a sliding-window mode, the first and last buckets will be wrong and that's fair. I can then do a TIMECLIP to remove the faulty buckets.

My proposal is to offer two new functions:

* DROPFIRSTBUCKETS (or REMOVE, I'm not sure about the right choice of name)
* DROPLASTBUCKETS (or REMOVE, I'm not sure about the right choice of name)

Each function will take a list of bucketized GTS or a single GTS, then a number of buckets to drop. The result will be the list of GTS with the dropped buckets.

To be more generic, we may also add functions to add buckets at the beginning or the end, that will automatically deal with bucketspan to add the right timestamp for the new datapoint, but that's not my primary need.

I will be more than happy to add these functions!

**Comment by hbs** [comment]
Can't you use SHRINK?

**Comment by hbs** [comment]
Or you can call BUCKETIZE with bucketizer.last and adapted last bucket + bucketcount

**Comment by PierreZ** [comment]
I don't think SHRINK or bucketizer.last will help me to have clear control on what I'm removing. Here's the type of WarpScript that I want to write:

```
[ SWAP mapper.whatever $pre $post 0 ] MAP
$pre DROPFIRSTBUCKETS
$post DROPLASTBUCKETS
```

**Comment by hbs** [comment]
You have complete control of what you want to remove using BUCKETIZE as you can chose the last bucket timestamp, the span and the count to remove buckets on either end of the GTS.

If your GTS is filled, you can also use STRICTMAPPER to only apply the mapper on windows which have the specified number of elements.

**Comment by PierreZ** [comment]
Yes, but using this method, I need to deal with bucket timestamp, span and count. I was thinking about dealing with buckets in the case of bucketized GTS.

**Comment by hbs** [comment]
Timestamp of the last bucket, bucket span and bucket count can be extracted from a GTS using the functions

LASTBUCKET
BUCKETSPAN
BUCKETCOUNT

It's then very easy to build a macro which does what you want.

**Comment by PierreZ** [comment]
Ok, I'll do a macro, thanks!
