### ISSUE TITLE
Inconsistency between fetch and find endpoints when using attributes

### ISSUE THREAD

**Issue by julien-girard** [cityzendata/warp10-platform#227]
When used, the find endpoint display every GTS with it's associated labels. The fetch endpoint does not.

Output sample :

    $ curl -H "X-Warp10-Token: ****" "${WARP_FETCH_ENDPOINT}?sortmeta&selector=${selector}&now=${LONG_MAXVALUE}&timespan=-1"
    $ 1500902560059000// class1{label1=label1,.app=test.titi} 0

    $ curl -H "X-Warp10-Token: ****" "${WARP_FIND_ENDPOINT}?sortmeta&selector=${selector}"
    $ class1{label1=label1,.app=test.titi}{attribute1=attribute1}

These could leeds to issues when comparing those two outputs to delete GTS without data points.

**Comment by hbs** [comment]
You mean the /fetch endpoint does not include the attributes by default?

You can display them by adding the 'showattr=true' parameter value to your /fetch URL.

Concerning sortmeta, if you want it to be taken into account you need to set 'sortmeta=true'.

Note that the attributes are not part of the identifier of a GTS, only the class and the labels are.
