### ISSUE TITLE
Support pushing attributes via /update endpoint 

### ISSUE THREAD

**Issue by StevenLeRoux** [cityzendata/warp10-platform#234]
Pushing attributes directly from an update endpoint can be useful in some situations.

A source would push measurements within the form "class{labels}{attributes} value".
When a cache entry expires, attributes would be taken into account and pushed in a metadata message. 

Attributes from Metadata messages would merged with current attributes for a given GTS. 
Metadata messages that don't embed attributes would not impact existing attributes.

As attributes are not part of the cache key, this has to be considered as a best effort meta update in contrast to what /meta provides.

Also, meta pushed via /update could conflict with /meta. The consistency between both is left as a user strategy. 

TODO : 

- distributed / update : DONE #233 
- distributed / streaming : DONE #233 
- standalone / update : DONE #233 
- standalone / streaming : DONE #233

**Comment by StevenLeRoux** [comment]
update : 

- distributed / streaming : DONE #233 
- standalone / update : DONE #233 
- standalone / streaming : DONE #233

**Comment by StevenLeRoux** [comment]
Can we merge this?

**Comment by hbs** [comment]
This PR does not solve the problem in a sufficiently generic and complete way, please check PR #260 to see if it fits your needs.

**Comment by StevenLeRoux** [comment]
I would have prefered few comments on what was missing in the current PR...  but anyway, #260 should do the job.

**Comment by hbs** [comment]
Comments was made on dec 7 2017 in the PR conversation, none of the PR latter commits actually addressed those comments.

**Comment by StevenLeRoux** [comment]
This issue has been created from the comments.  

> Please open an enhancement issue to track progress around this feature request.

 If something was missing, it was a good place to share them.
