### ISSUE TITLE
Expose platform limits 

### ISSUE THREAD

**Issue by FlorentinDUBOIS** [cityzendata/warp10-platform#238]
Hello!

We are able to set some platform limits, so it will be good to have access to these values. 
Furthermore, it will also be interesting to have access to the platform hard limits.

This feature includes:

- MAXOPS
- MAXBUCKETS
- MAXDEPTH
- MAXGTS
- MAXLONG
- MAXLOOP
- MAXPIXELS
- MAXSYMBOLS

Here, an example using the max ops limit:

```
'...' 'token' STORE

$token AUTHENTICATE

100000 MAXOPS

GETMAXOPS

GETHARDMAXOPS
```

The `GETMAXOPS` operand will push in the stack the current value of max ops (100000).

The `GETHARDMAXOPS` operand will push in the stack the hard max ops value.

**Comment by hbs** [comment]
All stack attributes can already be queried and put on the stack by calling STACKATTRIBUTE, i.e.
'fetch.limit.hard' STACKATTRIBUTE.
