### ISSUE TITLE
Update quantum version on standalone

### ISSUE THREAD

**Issue by LostInBrittany** [cityzendata/warp10-platform#243]
Currently warp10-standalone is shipped with an outdated quantum, 2.6.7.
Would it be possible to update the embedded quantum to 3.x?
Thanks!

**Comment by hbs** [comment]
There is no stable 3.x version of quantum, the latests 3.0.0-rc1 still has issues with annotations.

**Comment by LostInBrittany** [comment]
Oh crap! I was sure it was solved on last version. Could you please put an issue on warp10-quantum with a warpscript sample that worked on 2.6.7 and not in 3.0.0-rc1? I can try to get a fix for that quickly,

**Comment by hbs** [comment]
Done as part of the 1.2.13 release
