### ISSUE TITLE
Feature: support linit parameter on /find

### ISSUE THREAD

**Issue by miton18** [cityzendata/warp10-platform#255]
Any call to /find return the complete list of all matching GTS from the Directory.

It could be awesome to add a __limit__ on /api/v0/find parameters which will close the response when the count of GTS reach the limit.

**Comment by hbs** [comment]
Given the order is not guaranteed when you have directory sharding this is not something wise to implement.

If you want to limit your results to the first N, you can stop reading the result of the call to /find after that many results.

**Comment by miton18** [comment]
For lots of use cases, the order doesn't matter.

I'm agree, the request can be stopped when the count of entries is reached but in a browser context (for UI purpose) a request cannot be stopped until the end.

Execute a Warpscript with FIND and SUBLIST can be an answer but this will load all account GTS which cannot be done on some huge accounts.

**Comment by miton18** [comment]
Awesome ! Thanks.
