### ISSUE TITLE
Warp10 standalone: quantum seems broken in release 1.2.13

### ISSUE THREAD

**Issue by BlackYoup** [cityzendata/warp10-platform#258]
I wanted to start a standalone version of Warp10 `1.2.13`. When I load quantum, I end up on a page that shows the content of a directory with one file inside: `.touch`. Quantum bundled with version `1.2.11` of warp10 standalone works fine with the same configuration. I didn't try the `1.2.12` versions.

I downloaded Warp10@1.2.13 on Bintray.

**Comment by Giwi** [comment]
Indeed, we had a broken build. The next release aim to fix that (very soon).

**Comment by LostInBrittany** [comment]
This is fixed, isn't it ? :)

**Comment by hbs** [comment]
Fixed in 1.2.14
