### ISSUE TITLE
TRY function behavior

### ISSUE THREAD

**Issue by LostInBrittany** [cityzendata/warp10-platform#272]
Hi!
We were trying to use the [`TRY`](https://github.com/cityzendata/warp10-platform/blob/d9429ee70e9e175dd6f04f912eb37684ba777eb6/warp10/src/main/java/io/warp10/script/functions/TRY.java) function to detect is a certain function was defined in a custom Warp 10 instance, something like:

```
<% A_FUNCTION_NAME %>
<% 'Function doesn't exist' %>
<% 'Finally do something' %>
TRY
``` 

> To be sure that we understand the `TRY` function, we did several tests:
> 
> ```
> <% 'Nothing in error here' %>
> <% 'Catching an error' %>
> <% 'Finally do something' %>
> TRY
> ``` 
>  and we get the expected result:
> 
> ```
> 0: "Finally do something"
> 1: "Nothing in error here"
> ```
> 
> And:
> 
> ```
> <% "Let's fail hard" FAIL %>
> <% 'Catching an error' %>
> <% 'Finally do something' %>
> TRY
> ``` 
> and we also get the expected result:
> 
> ```
> 0: "Finally do something"
> 1: "Catching an error"
> 2: "Nothing in error here"
> ```

So we tested our snippet with an undefined function:

```
<% UNDEFINEDFUNCTION %>
<% 'Catching an error' %>
<% 'Finally do something' %>
TRY
``` 
and instead of the expected  result, we got:

`ERROR line #1: in section '[TOP]': Unknown function 'UNDEFINEDFUNCTION'`

Any idea of why the `Unknown function` error doesn't get caught?

**Comment by rdejoux** [comment]
In your case the macro is parsed before the TRY was called. So the error occur during the parsing.
With a string and EVAL the parsing error is raised in the TRY:

With no error:
```
<% '2 3 *' EVAL %>
<% 'Catching an error' %>
<% 'Finally do something' %>
TRY
```
Result:
```
0: "Finally do something"
1: 6
```
With error:
```
<% 'UNDEFINEFUNCTION' EVAL %>
<% 'Catching an error' %>
<% 'Finally do something' %>
TRY
```
Result:
```
0: "Finally do something"
1: "Catching an error"
```

**Comment by LostInBrittany** [comment]
Oh, my bad, I should have thought about it, macros are parsed even if not executed, so the error arrives in parsing time, so there is no way the `TRY` does anything there... We will go with the `EVAL` solution, thanks @rdejoux !
