### ISSUE TITLE
[Warp10 Stadalone] Enforce levelDB backend

### ISSUE THREAD

**Issue by waxzce** [cityzendata/warp10-platform#278]
As level DB crash survival is currently tested by the warp10 team on JNI binding only and some strange behavior happen on the java port, I suggest a new default for standalone instance:
- if the  levelDBJNI backend cannot be load, crash the startup process of Warp10 with an explicit error.
- If a env variable (or anything else to pass info) like EXPERIMENTAL_NON_JNI_LEVELDB_BACKEND_ALLOWED is set to true, just log a warning and let the startup process execute. 

This way will guarantee the consistency of levelDB implementation usage.

**Comment by hbs** [comment]
We have no evidence of any difference between the native and Java implementations of LevelDB, nevertheless PR #282 has been created to allow more control on LevelDB implementations.
